title: Karthik's Github Pages Story
author: Karthi KN
email: karthikingithub@github.com
description: > # this means to ignore newlines until "baseurl:"
Creating my blog to share experience of learning 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/karthikingithub # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
